### ISSUE TITLE
Update Google Play Service dependency to 6.5.+

### ISSUE THREAD

**Issue by f2prateek** [quantcast/android-measurement#10]

**Comment by f2prateek** [comment]
Related to #11

**Comment by SmithKevin** [comment]
This should be fixed now.   The 1.2.6 version of the SDK uses the new split libraries of Google Play Services.    This is so when using the Quantcast SDK, you do not need to pull in the entire play library which is huge and people were having issues hitting the 65,536 method limit. 

However it looks like people are running into issues where they are not using the split library and thus getting duplicate errors.   We recommend moving the the split play library structure a it has more benefits, but for backwards compatibility, I will create another library that depends on the full Play services.

The documentation will also be updated to reflect these changes.

**Comment by pang0018** [comment]
Thanks!

**Comment by SmithKevin** [comment]
Documentation has been updated.   This should be working now.  Let me know if you are still running into issues.
