### ISSUE TITLE
Update Maven Central

### ISSUE THREAD

**Issue by ODC-Dev** [quantcast/android-measurement#13]
Could you possibly update Maven Central to include the latest build? The latest in Maven is 1.2.6, but the current committed code is tagged 1.3.0.

**Comment by SmithKevin** [comment]
We post everything to JCenter which is android's default maven repository.  However this is supposed to automatically sync with the Maven Central repository.  I'll check while that sync didn't take place, but in the mean time you could also add jcenter() to your projects gradle repository list and then you should get the latest.

**Comment by SmithKevin** [comment]
These have now been synced to Maven Central.
