### ISSUE TITLE
Documentation: gradle version is obsolete

### ISSUE THREAD

**Issue by yairkukielka** [quantcast/android-measurement#14]
Could you change this:
'com.quantcast.android.measurement:QuantcastAndroidSdk-split:1.2.+'
to this:
'com.quantcast.android.measurement:QuantcastAndroidSdk-split:1.3.+'

on the documentation?  Otherwise, this won't compile:
QuantcastClient.startQuantcast(context, "api_key", userIdentifier, audienceSegments);

**Comment by SmithKevin** [comment]
Doc updated
