### ISSUE TITLE
Remove play-services-ads dependency, use play-services-basement instead

### ISSUE THREAD

**Issue by dlew** [quantcast/android-measurement#15]
As far as I know, the only reason quantcast uses play-services-ads is to get the advertising ID. With the latest releases of Google Play Services you can now do this via play-services-basement.

Switching to using play-services-basement would be a huge dex method count win for apps such as ours which don't advertise, but just use advertising ID for tracking.

**Comment by SmithKevin** [comment]
Awesome. You are correct, we only need the ad ID.  I will into switching to basement this week.   Thanks for the heads up.

**Comment by dlew** [comment]
Ping! Would like to see this change so we can reduce method count.

**Comment by SmithKevin** [comment]
This has been released under 
'com.quantcast.android.measurement:QuantcastAndroidSdk-split:1.3.2'

The only update is in the maven repository.  The ads dependency has been replaced with play-services-basement.  Let me know if there are any issues.

**Comment by dlew** [comment]
This is great, thanks!
